<?php namespace App\HL7\FHIR\DSTU2;

/*!
 * This class was generated with the PHPFHIR library (https://github.com/dcarbone/php-fhir) using
 * class definitions from HL7 FHIR (https://www.hl7.org/fhir/)
 * 
 * Class creation date: April 8th, 2019
 * 
 * PHPFHIR Copyright:
 * 
 * Copyright 2016-2019 Daniel Carbone (daniel.p.carbone@gmail.com)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 */

class PHPFHIRAutoloader
{
    const ROOT_DIR = __DIR__;

    /** @var array */
    private static $_classMap = array (
  'App\\HL7\\FHIR\\DSTU2\\PHPFHIRParserMap' => 'App/HL7/FHIR/DSTU2/PHPFHIRParserMap.php',
  'App\\HL7\\FHIR\\DSTU2\\PHPFHIRHelper' => 'App/HL7/FHIR/DSTU2/PHPFHIRHelper.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRMarkdown' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRMarkdown.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRInteger' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRInteger.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDateTime' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDateTime.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRUnsignedInt' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRUnsignedInt.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDate' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDate.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDecimal' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDecimal.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRUri' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRUri.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRId' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRId.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRBase64Binary' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRBase64Binary.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRTime' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRTime.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIROid' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIROid.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRPositiveInt' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRPositiveInt.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRString' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRString.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRBoolean' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRBoolean.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRUuid' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRUuid.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRInstant' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRInstant.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResourceContainer' => 'App/HL7/FHIR/DSTU2/FHIRResourceContainer.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRExtension' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRExtension.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRBackboneElement' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRBackboneElement.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRNarrative' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRNarrative.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRNarrativeStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRNarrativeStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement' => 'App/HL7/FHIR/DSTU2/FHIRElement.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRPeriod' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRPeriod.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCoding' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCoding.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRRange' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRRange.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuantity' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuantity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuantityComparator' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuantityComparator.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAttachment' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAttachment.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRRatio' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRRatio.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAnnotation' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAnnotation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSampledData' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSampledData.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSampledDataDataType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSampledDataDataType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRReference' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRReference.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCodeableConcept' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCodeableConcept.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRIdentifier' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRIdentifier.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRIdentifierUse' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRIdentifierUse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSignature' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSignature.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuantity\\FHIRAge' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuantity/FHIRAge.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuantity\\FHIRCount' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuantity/FHIRCount.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuantity\\FHIRMoney' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuantity/FHIRMoney.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuantity\\FHIRDistance' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuantity/FHIRDistance.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuantity\\FHIRDuration' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuantity/FHIRDuration.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuantity\\FHIRSimpleQuantity' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuantity/FHIRSimpleQuantity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRElementDefinition' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRElementDefinition.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionMapping' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRElementDefinition/FHIRElementDefinitionMapping.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionSlicing' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRElementDefinition/FHIRElementDefinitionSlicing.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionBinding' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRElementDefinition/FHIRElementDefinitionBinding.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionType' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRElementDefinition/FHIRElementDefinitionType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionBase' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRElementDefinition/FHIRElementDefinitionBase.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRElementDefinition\\FHIRElementDefinitionConstraint' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRElementDefinition/FHIRElementDefinitionConstraint.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRPropertyRepresentation' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRPropertyRepresentation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSlicingRules' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSlicingRules.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRBindingStrength' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRBindingStrength.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAggregationMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAggregationMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRConstraintSeverity' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRConstraintSeverity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRTiming' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRTiming.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTiming\\FHIRTimingRepeat' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTiming/FHIRTimingRepeat.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRUnitsOfTime' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRUnitsOfTime.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIREventTiming' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIREventTiming.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAddress' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAddress.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAddressUse' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAddressUse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAddressType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAddressType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRHumanName' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRHumanName.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRNameUse' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRNameUse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRMeta' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRMeta.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRContactPoint' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRContactPoint.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRContactPointSystem' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRContactPointSystem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRContactPointUse' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRContactPointUse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource' => 'App/HL7/FHIR/DSTU2/FHIRResource.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDomainResource' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDomainResource.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRNoteType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRNoteType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDocumentReferenceStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDocumentReferenceStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRConceptMapEquivalence' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRConceptMapEquivalence.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRRemittanceOutcome' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRRemittanceOutcome.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRConformanceResourceStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRConformanceResourceStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAdministrativeGender' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAdministrativeGender.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSearchParamType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSearchParamType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRBinary' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRBinary.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRLocation' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRLocation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRLocation\\FHIRLocationPosition' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRLocation/FHIRLocationPosition.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRLocationStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRLocationStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRLocationMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRLocationMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRNutritionOrder' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRNutritionOrder.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderOralDiet' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderOralDiet.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderNutrient' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderNutrient.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderTexture' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderTexture.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderSupplement' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderSupplement.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderEnteralFormula' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderEnteralFormula.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRNutritionOrder\\FHIRNutritionOrderAdministration' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRNutritionOrder/FHIRNutritionOrderAdministration.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRNutritionOrderStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRNutritionOrderStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDevice' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDevice.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDeviceStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDeviceStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRPaymentNotice' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRPaymentNotice.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRComposition' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRComposition.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRComposition\\FHIRCompositionAttester' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRComposition/FHIRCompositionAttester.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRComposition\\FHIRCompositionEvent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRComposition/FHIRCompositionEvent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRComposition\\FHIRCompositionSection' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRComposition/FHIRCompositionSection.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCompositionStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCompositionStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCompositionAttestationMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCompositionAttestationMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRCommunication' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRCommunication.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRCommunication\\FHIRCommunicationPayload' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRCommunication/FHIRCommunicationPayload.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCommunicationStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCommunicationStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIREncounter' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIREncounter.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIREncounter\\FHIREncounterStatusHistory' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIREncounter/FHIREncounterStatusHistory.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIREncounter\\FHIREncounterParticipant' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIREncounter/FHIREncounterParticipant.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIREncounter\\FHIREncounterHospitalization' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIREncounter/FHIREncounterHospitalization.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIREncounter\\FHIREncounterLocation' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIREncounter/FHIREncounterLocation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIREncounterLocationStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIREncounterLocationStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIREncounterClass' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIREncounterClass.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIREncounterState' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIREncounterState.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIREpisodeOfCare' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIREpisodeOfCare.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIREpisodeOfCare\\FHIREpisodeOfCareStatusHistory' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIREpisodeOfCare/FHIREpisodeOfCareStatusHistory.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIREpisodeOfCare\\FHIREpisodeOfCareCareTeam' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIREpisodeOfCare/FHIREpisodeOfCareCareTeam.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIREpisodeOfCareStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIREpisodeOfCareStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRCommunicationRequest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRCommunicationRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRCommunicationRequest\\FHIRCommunicationRequestPayload' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRCommunicationRequest/FHIRCommunicationRequestPayload.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCommunicationRequestStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCommunicationRequestStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRSchedule' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRSchedule.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIREligibilityRequest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIREligibilityRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRProcedure' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRProcedure.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRProcedure\\FHIRProcedurePerformer' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRProcedure/FHIRProcedurePerformer.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRProcedure\\FHIRProcedureFocalDevice' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRProcedure/FHIRProcedureFocalDevice.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRProcedureStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRProcedureStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRAppointmentResponse' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRAppointmentResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRParticipantStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRParticipantStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRSupplyDelivery' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRSupplyDelivery.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSupplyDeliveryStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSupplyDeliveryStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRMedicationStatement' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRMedicationStatement.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedicationStatement\\FHIRMedicationStatementDosage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedicationStatement/FHIRMedicationStatementDosage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRMedicationStatementStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRMedicationStatementStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRConceptMap' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRConceptMap.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConceptMap\\FHIRConceptMapContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConceptMap/FHIRConceptMapContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConceptMap\\FHIRConceptMapElement' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConceptMap/FHIRConceptMapElement.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConceptMap\\FHIRConceptMapTarget' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConceptMap/FHIRConceptMapTarget.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConceptMap\\FHIRConceptMapDependsOn' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConceptMap/FHIRConceptMapDependsOn.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIREnrollmentRequest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIREnrollmentRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRPractitioner' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRPractitioner.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPractitioner\\FHIRPractitionerPractitionerRole' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPractitioner/FHIRPractitionerPractitionerRole.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPractitioner\\FHIRPractitionerQualification' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPractitioner/FHIRPractitionerQualification.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRFamilyMemberHistory' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRFamilyMemberHistory.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRFamilyMemberHistory\\FHIRFamilyMemberHistoryCondition' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRFamilyMemberHistory/FHIRFamilyMemberHistoryCondition.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRFamilyHistoryStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRFamilyHistoryStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRAuditEvent' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRAuditEvent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventEvent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRAuditEvent/FHIRAuditEventEvent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventParticipant' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRAuditEvent/FHIRAuditEventParticipant.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventNetwork' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRAuditEvent/FHIRAuditEventNetwork.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventSource' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRAuditEvent/FHIRAuditEventSource.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventObject' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRAuditEvent/FHIRAuditEventObject.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRAuditEvent\\FHIRAuditEventDetail' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRAuditEvent/FHIRAuditEventDetail.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAuditEventAction' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAuditEventAction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAuditEventOutcome' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAuditEventOutcome.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAuditEventParticipantNetworkType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAuditEventParticipantNetworkType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRClinicalImpression' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRClinicalImpression.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClinicalImpression\\FHIRClinicalImpressionInvestigations' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClinicalImpression/FHIRClinicalImpressionInvestigations.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClinicalImpression\\FHIRClinicalImpressionFinding' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClinicalImpression/FHIRClinicalImpressionFinding.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClinicalImpression\\FHIRClinicalImpressionRuledOut' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClinicalImpression/FHIRClinicalImpressionRuledOut.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRClinicalImpressionStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRClinicalImpressionStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIROrganization' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIROrganization.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIROrganization\\FHIROrganizationContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIROrganization/FHIROrganizationContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRVisionPrescription' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRVisionPrescription.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRVisionPrescription\\FHIRVisionPrescriptionDispense' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRVisionPrescription/FHIRVisionPrescriptionDispense.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRVisionBase' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRVisionBase.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRVisionEyes' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRVisionEyes.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDetectedIssue' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDetectedIssue.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDetectedIssue\\FHIRDetectedIssueMitigation' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDetectedIssue/FHIRDetectedIssueMitigation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDetectedIssueSeverity' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDetectedIssueSeverity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRClaimResponse' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRClaimResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseItem' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseItem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseDetail' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseDetail.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication1' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication1.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseSubDetail' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseSubDetail.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication2' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication2.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAddItem' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseAddItem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication3' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication3.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseDetail1' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseDetail1.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseAdjudication4' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseAdjudication4.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseError' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseError.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseNote' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseNote.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaimResponse\\FHIRClaimResponseCoverage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaimResponse/FHIRClaimResponseCoverage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRTestScript' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRTestScript.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptMetadata' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptMetadata.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptLink' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptLink.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptCapability' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptCapability.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptFixture' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptFixture.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptVariable' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptVariable.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptSetup' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptSetup.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptAction' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptAction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptOperation' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptOperation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptRequestHeader' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptRequestHeader.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptAssert' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptAssert.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptTest' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptTest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptAction1' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptAction1.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptTeardown' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptTeardown.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRTestScript\\FHIRTestScriptAction2' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRTestScript/FHIRTestScriptAction2.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAssertionDirectionType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAssertionDirectionType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAssertionResponseTypes' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAssertionResponseTypes.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAssertionOperatorType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAssertionOperatorType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRContentType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRContentType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIREnrollmentResponse' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIREnrollmentResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRContract' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRContract.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractActor' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractActor.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractValuedItem' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractValuedItem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractSigner' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractSigner.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractTerm' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractTerm.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractActor1' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractActor1.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractValuedItem1' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractValuedItem1.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractFriendly' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractFriendly.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractLegal' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractLegal.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRContract\\FHIRContractRule' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRContract/FHIRContractRule.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDiagnosticReport' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDiagnosticReport.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDiagnosticReport\\FHIRDiagnosticReportImage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDiagnosticReport/FHIRDiagnosticReportImage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDiagnosticReportStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDiagnosticReportStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRImmunizationRecommendation' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRImmunizationRecommendation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImmunizationRecommendation\\FHIRImmunizationRecommendationRecommendation' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImmunizationRecommendation/FHIRImmunizationRecommendationRecommendation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImmunizationRecommendation\\FHIRImmunizationRecommendationDateCriterion' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImmunizationRecommendation/FHIRImmunizationRecommendationDateCriterion.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImmunizationRecommendation\\FHIRImmunizationRecommendationProtocol' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImmunizationRecommendation/FHIRImmunizationRecommendationProtocol.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRSpecimen' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRSpecimen.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRSpecimen\\FHIRSpecimenCollection' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRSpecimen/FHIRSpecimenCollection.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRSpecimen\\FHIRSpecimenTreatment' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRSpecimen/FHIRSpecimenTreatment.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRSpecimen\\FHIRSpecimenContainer' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRSpecimen/FHIRSpecimenContainer.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSpecimenStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSpecimenStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRBasic' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRBasic.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRImagingStudy' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRImagingStudy.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImagingStudy\\FHIRImagingStudySeries' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImagingStudy/FHIRImagingStudySeries.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImagingStudy\\FHIRImagingStudyInstance' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImagingStudy/FHIRImagingStudyInstance.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRInstanceAvailability' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRInstanceAvailability.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDeviceComponent' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDeviceComponent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDeviceComponent\\FHIRDeviceComponentProductionSpecification' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDeviceComponent/FHIRDeviceComponentProductionSpecification.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRMeasmnt_Principle' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRMeasmnt_Principle.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRSubstance' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRSubstance.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRSubstance\\FHIRSubstanceInstance' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRSubstance/FHIRSubstanceInstance.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRSubstance\\FHIRSubstanceIngredient' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRSubstance/FHIRSubstanceIngredient.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIROperationOutcome' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIROperationOutcome.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIROperationOutcome\\FHIROperationOutcomeIssue' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIROperationOutcome/FHIROperationOutcomeIssue.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRIssueType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRIssueType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRIssueSeverity' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRIssueSeverity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRMedia' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRMedia.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDigitalMediaType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDigitalMediaType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRParameters' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRParameters.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRParameters\\FHIRParametersParameter' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRParameters/FHIRParametersParameter.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRCondition' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRCondition.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRCondition\\FHIRConditionStage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRCondition/FHIRConditionStage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRCondition\\FHIRConditionEvidence' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRCondition/FHIRConditionEvidence.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRConditionVerificationStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRConditionVerificationStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRCarePlan' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRCarePlan.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRCarePlan\\FHIRCarePlanRelatedPlan' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRCarePlan/FHIRCarePlanRelatedPlan.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRCarePlan\\FHIRCarePlanParticipant' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRCarePlan/FHIRCarePlanParticipant.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRCarePlan\\FHIRCarePlanActivity' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRCarePlan/FHIRCarePlanActivity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRCarePlan\\FHIRCarePlanDetail' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRCarePlan/FHIRCarePlanDetail.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCarePlanStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCarePlanStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCarePlanRelationship' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCarePlanRelationship.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRCarePlanActivityStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRCarePlanActivityStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRMedication' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRMedication.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedication\\FHIRMedicationProduct' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedication/FHIRMedicationProduct.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedication\\FHIRMedicationIngredient' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedication/FHIRMedicationIngredient.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedication\\FHIRMedicationBatch' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedication/FHIRMedicationBatch.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedication\\FHIRMedicationPackage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedication/FHIRMedicationPackage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedication\\FHIRMedicationContent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedication/FHIRMedicationContent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDeviceMetric' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDeviceMetric.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDeviceMetric\\FHIRDeviceMetricCalibration' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDeviceMetric/FHIRDeviceMetricCalibration.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDeviceMetricColor' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDeviceMetricColor.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDeviceMetricCalibrationState' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDeviceMetricCalibrationState.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDeviceMetricCalibrationType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDeviceMetricCalibrationType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDeviceMetricCategory' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDeviceMetricCategory.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDeviceMetricOperationalStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDeviceMetricOperationalStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRProcessRequest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRProcessRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRProcessRequest\\FHIRProcessRequestItem' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRProcessRequest/FHIRProcessRequestItem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRActionList' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRActionList.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRCoverage' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRCoverage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRProvenance' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRProvenance.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRProvenance\\FHIRProvenanceAgent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRProvenance/FHIRProvenanceAgent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRProvenance\\FHIRProvenanceRelatedAgent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRProvenance/FHIRProvenanceRelatedAgent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRProvenance\\FHIRProvenanceEntity' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRProvenance/FHIRProvenanceEntity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRProvenanceEntityRole' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRProvenanceEntityRole.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRNamingSystem' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRNamingSystem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRNamingSystem\\FHIRNamingSystemContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRNamingSystem/FHIRNamingSystemContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRNamingSystem\\FHIRNamingSystemUniqueId' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRNamingSystem/FHIRNamingSystemUniqueId.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRNamingSystemType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRNamingSystemType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRNamingSystemIdentifierType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRNamingSystemIdentifierType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRPatient' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRPatient.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPatient\\FHIRPatientContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPatient/FHIRPatientContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPatient\\FHIRPatientAnimal' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPatient/FHIRPatientAnimal.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPatient\\FHIRPatientCommunication' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPatient/FHIRPatientCommunication.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPatient\\FHIRPatientLink' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPatient/FHIRPatientLink.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRLinkType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRLinkType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDeviceUseRequest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDeviceUseRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDeviceUseRequestStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDeviceUseRequestStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDeviceUseRequestPriority' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDeviceUseRequestPriority.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRQuestionnaire' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRQuestionnaire.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRQuestionnaire\\FHIRQuestionnaireGroup' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRQuestionnaire/FHIRQuestionnaireGroup.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRQuestionnaire\\FHIRQuestionnaireQuestion' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRQuestionnaire/FHIRQuestionnaireQuestion.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuestionnaireStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuestionnaireStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAnswerFormat' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAnswerFormat.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRImplementationGuide' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRImplementationGuide.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuideContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImplementationGuide/FHIRImplementationGuideContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuideDependency' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImplementationGuide/FHIRImplementationGuideDependency.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuidePackage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImplementationGuide/FHIRImplementationGuidePackage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuideResource' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImplementationGuide/FHIRImplementationGuideResource.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuideGlobal' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImplementationGuide/FHIRImplementationGuideGlobal.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImplementationGuide\\FHIRImplementationGuidePage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImplementationGuide/FHIRImplementationGuidePage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRGuideDependencyType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRGuideDependencyType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRGuideResourcePurpose' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRGuideResourcePurpose.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRGuidePageKind' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRGuidePageKind.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIROrder' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIROrder.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIROrder\\FHIROrderWhen' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIROrder/FHIROrderWhen.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRAppointment' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRAppointment.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRAppointment\\FHIRAppointmentParticipant' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRAppointment/FHIRAppointmentParticipant.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRParticipantRequired' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRParticipantRequired.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAppointmentStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAppointmentStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRParticipationStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRParticipationStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRBodySite' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRBodySite.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRClaim' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRClaim.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaim\\FHIRClaimPayee' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaim/FHIRClaimPayee.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaim\\FHIRClaimDiagnosis' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaim/FHIRClaimDiagnosis.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaim\\FHIRClaimCoverage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaim/FHIRClaimCoverage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaim\\FHIRClaimItem' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaim/FHIRClaimItem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaim\\FHIRClaimDetail' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaim/FHIRClaimDetail.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaim\\FHIRClaimSubDetail' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaim/FHIRClaimSubDetail.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaim\\FHIRClaimProsthesis' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaim/FHIRClaimProsthesis.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRClaim\\FHIRClaimMissingTeeth' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRClaim/FHIRClaimMissingTeeth.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRClaimType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRClaimType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRUse' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRUse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRStructureDefinition' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRStructureDefinition.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRStructureDefinition\\FHIRStructureDefinitionContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRStructureDefinition/FHIRStructureDefinitionContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRStructureDefinition\\FHIRStructureDefinitionMapping' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRStructureDefinition/FHIRStructureDefinitionMapping.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRStructureDefinition\\FHIRStructureDefinitionSnapshot' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRStructureDefinition/FHIRStructureDefinitionSnapshot.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRStructureDefinition\\FHIRStructureDefinitionDifferential' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRStructureDefinition/FHIRStructureDefinitionDifferential.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRStructureDefinitionKind' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRStructureDefinitionKind.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRExtensionContext' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRExtensionContext.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDataElement' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDataElement.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDataElement\\FHIRDataElementContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDataElement/FHIRDataElementContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDataElement\\FHIRDataElementMapping' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDataElement/FHIRDataElementMapping.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDataElementStringency' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDataElementStringency.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRAllergyIntolerance' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRAllergyIntolerance.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRAllergyIntolerance\\FHIRAllergyIntoleranceReaction' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRAllergyIntolerance/FHIRAllergyIntoleranceReaction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAllergyIntoleranceCertainty' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAllergyIntoleranceCertainty.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAllergyIntoleranceType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAllergyIntoleranceType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAllergyIntoleranceSeverity' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAllergyIntoleranceSeverity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAllergyIntoleranceCriticality' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAllergyIntoleranceCriticality.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAllergyIntoleranceCategory' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAllergyIntoleranceCategory.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAllergyIntoleranceStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAllergyIntoleranceStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRGroup' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRGroup.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRGroup\\FHIRGroupCharacteristic' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRGroup/FHIRGroupCharacteristic.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRGroup\\FHIRGroupMember' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRGroup/FHIRGroupMember.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRGroupType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRGroupType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRProcessResponse' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRProcessResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRProcessResponse\\FHIRProcessResponseNotes' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRProcessResponse/FHIRProcessResponseNotes.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRProcedureRequest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRProcedureRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRProcedureRequestPriority' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRProcedureRequestPriority.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRProcedureRequestStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRProcedureRequestStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRValueSet' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRValueSet.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetCodeSystem' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetCodeSystem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetConcept' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetConcept.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetDesignation' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetDesignation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetCompose' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetCompose.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetInclude' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetInclude.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetConcept1' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetConcept1.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetFilter' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetFilter.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetExpansion' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetExpansion.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetParameter' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetParameter.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRValueSet\\FHIRValueSetContains' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRValueSet/FHIRValueSetContains.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRFilterOperator' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRFilterOperator.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRObservation' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRObservation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRObservation\\FHIRObservationReferenceRange' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRObservation/FHIRObservationReferenceRange.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRObservation\\FHIRObservationRelated' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRObservation/FHIRObservationRelated.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRObservation\\FHIRObservationComponent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRObservation/FHIRObservationComponent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRObservationStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRObservationStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRObservationRelationshipType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRObservationRelationshipType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRFlag' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRFlag.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRFlagStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRFlagStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRRelatedPerson' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRRelatedPerson.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDiagnosticOrder' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDiagnosticOrder.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDiagnosticOrder\\FHIRDiagnosticOrderEvent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDiagnosticOrder/FHIRDiagnosticOrderEvent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDiagnosticOrder\\FHIRDiagnosticOrderItem' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDiagnosticOrder/FHIRDiagnosticOrderItem.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDiagnosticOrderStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDiagnosticOrderStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDiagnosticOrderPriority' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDiagnosticOrderPriority.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRImmunization' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRImmunization.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImmunization\\FHIRImmunizationExplanation' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImmunization/FHIRImmunizationExplanation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImmunization\\FHIRImmunizationReaction' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImmunization/FHIRImmunizationReaction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImmunization\\FHIRImmunizationVaccinationProtocol' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImmunization/FHIRImmunizationVaccinationProtocol.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRGoal' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRGoal.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRGoal\\FHIRGoalOutcome' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRGoal/FHIRGoalOutcome.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRGoalStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRGoalStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRReferralRequest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRReferralRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRReferralStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRReferralStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRSubscription' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRSubscription.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRSubscription\\FHIRSubscriptionChannel' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRSubscription/FHIRSubscriptionChannel.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSubscriptionStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSubscriptionStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSubscriptionChannelType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSubscriptionChannelType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRSearchParameter' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRSearchParameter.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRSearchParameter\\FHIRSearchParameterContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRSearchParameter/FHIRSearchParameterContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRXPathUsageType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRXPathUsageType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRConformance' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRConformance.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceSoftware' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceSoftware.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceImplementation' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceImplementation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceRest' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceRest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceSecurity' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceSecurity.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceCertificate' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceCertificate.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceResource' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceResource.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceInteraction' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceInteraction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceSearchParam' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceSearchParam.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceInteraction1' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceInteraction1.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceOperation' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceOperation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceMessaging' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceMessaging.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceEndpoint' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceEndpoint.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceEvent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceEvent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRConformance\\FHIRConformanceDocument' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRConformance/FHIRConformanceDocument.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDocumentMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDocumentMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSystemRestfulInteraction' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSystemRestfulInteraction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRResourceVersionPolicy' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRResourceVersionPolicy.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRRestfulConformanceMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRRestfulConformanceMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRTypeRestfulInteraction' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRTypeRestfulInteraction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRConditionalDeleteStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRConditionalDeleteStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRConformanceStatementKind' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRConformanceStatementKind.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSearchModifierCode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSearchModifierCode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRConformanceEventMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRConformanceEventMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRMessageSignificanceCategory' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRMessageSignificanceCategory.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRUnknownContentCode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRUnknownContentCode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRTransactionMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRTransactionMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDocumentReference' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDocumentReference.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDocumentReference\\FHIRDocumentReferenceRelatesTo' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDocumentReference/FHIRDocumentReferenceRelatesTo.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDocumentReference\\FHIRDocumentReferenceContent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDocumentReference/FHIRDocumentReferenceContent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDocumentReference\\FHIRDocumentReferenceContext' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDocumentReference/FHIRDocumentReferenceContext.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDocumentReference\\FHIRDocumentReferenceRelated' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDocumentReference/FHIRDocumentReferenceRelated.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDocumentRelationshipType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDocumentRelationshipType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRMedicationDispense' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRMedicationDispense.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedicationDispense\\FHIRMedicationDispenseDosageInstruction' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedicationDispense/FHIRMedicationDispenseDosageInstruction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedicationDispense\\FHIRMedicationDispenseSubstitution' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedicationDispense/FHIRMedicationDispenseSubstitution.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRMedicationDispenseStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRMedicationDispenseStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRMedicationOrder' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRMedicationOrder.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedicationOrder\\FHIRMedicationOrderDosageInstruction' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedicationOrder/FHIRMedicationOrderDosageInstruction.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedicationOrder\\FHIRMedicationOrderDispenseRequest' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedicationOrder/FHIRMedicationOrderDispenseRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedicationOrder\\FHIRMedicationOrderSubstitution' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedicationOrder/FHIRMedicationOrderSubstitution.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRMedicationOrderStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRMedicationOrderStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRList' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRList.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRList\\FHIRListEntry' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRList/FHIRListEntry.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRListStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRListStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRListMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRListMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRPerson' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRPerson.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPerson\\FHIRPersonLink' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPerson/FHIRPersonLink.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRIdentityAssuranceLevel' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRIdentityAssuranceLevel.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRBundle' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRBundle.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRBundle\\FHIRBundleLink' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRBundle/FHIRBundleLink.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRBundle\\FHIRBundleEntry' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRBundle/FHIRBundleEntry.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRBundle\\FHIRBundleSearch' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRBundle/FHIRBundleSearch.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRBundle\\FHIRBundleRequest' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRBundle/FHIRBundleRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRBundle\\FHIRBundleResponse' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRBundle/FHIRBundleResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRHTTPVerb' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRHTTPVerb.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSearchEntryMode' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSearchEntryMode.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRBundleType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRBundleType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRMessageHeader' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRMessageHeader.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMessageHeader\\FHIRMessageHeaderResponse' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMessageHeader/FHIRMessageHeaderResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMessageHeader\\FHIRMessageHeaderSource' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMessageHeader/FHIRMessageHeaderSource.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMessageHeader\\FHIRMessageHeaderDestination' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMessageHeader/FHIRMessageHeaderDestination.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRResponseType' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRResponseType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIREligibilityResponse' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIREligibilityResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRSlot' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRSlot.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSlotStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSlotStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRAccount' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRAccount.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRAccountStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRAccountStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIROrderResponse' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIROrderResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIROrderStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIROrderStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRSupplyRequest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRSupplyRequest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRSupplyRequest\\FHIRSupplyRequestWhen' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRSupplyRequest/FHIRSupplyRequestWhen.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRSupplyRequestStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRSupplyRequestStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRExplanationOfBenefit' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRExplanationOfBenefit.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDeviceUseStatement' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDeviceUseStatement.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRQuestionnaireResponse' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRQuestionnaireResponse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRQuestionnaireResponse\\FHIRQuestionnaireResponseGroup' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRQuestionnaireResponse/FHIRQuestionnaireResponseGroup.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRQuestionnaireResponse\\FHIRQuestionnaireResponseQuestion' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRQuestionnaireResponse/FHIRQuestionnaireResponseQuestion.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRQuestionnaireResponse\\FHIRQuestionnaireResponseAnswer' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRQuestionnaireResponse/FHIRQuestionnaireResponseAnswer.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRQuestionnaireResponseStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRQuestionnaireResponseStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRDocumentManifest' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRDocumentManifest.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDocumentManifest\\FHIRDocumentManifestContent' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDocumentManifest/FHIRDocumentManifestContent.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRDocumentManifest\\FHIRDocumentManifestRelated' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRDocumentManifest/FHIRDocumentManifestRelated.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRHealthcareService' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRHealthcareService.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRHealthcareService\\FHIRHealthcareServiceServiceType' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRHealthcareService/FHIRHealthcareServiceServiceType.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRHealthcareService\\FHIRHealthcareServiceAvailableTime' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRHealthcareService/FHIRHealthcareServiceAvailableTime.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRHealthcareService\\FHIRHealthcareServiceNotAvailable' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRHealthcareService/FHIRHealthcareServiceNotAvailable.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRDaysOfWeek' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRDaysOfWeek.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRPaymentReconciliation' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRPaymentReconciliation.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPaymentReconciliation\\FHIRPaymentReconciliationDetail' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPaymentReconciliation/FHIRPaymentReconciliationDetail.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRPaymentReconciliation\\FHIRPaymentReconciliationNote' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRPaymentReconciliation/FHIRPaymentReconciliationNote.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRImagingObjectSelection' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRImagingObjectSelection.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImagingObjectSelection\\FHIRImagingObjectSelectionStudy' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImagingObjectSelection/FHIRImagingObjectSelectionStudy.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImagingObjectSelection\\FHIRImagingObjectSelectionSeries' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImagingObjectSelection/FHIRImagingObjectSelectionSeries.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImagingObjectSelection\\FHIRImagingObjectSelectionInstance' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImagingObjectSelection/FHIRImagingObjectSelectionInstance.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRImagingObjectSelection\\FHIRImagingObjectSelectionFrames' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRImagingObjectSelection/FHIRImagingObjectSelectionFrames.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIROperationDefinition' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIROperationDefinition.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIROperationDefinition\\FHIROperationDefinitionContact' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIROperationDefinition/FHIROperationDefinitionContact.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIROperationDefinition\\FHIROperationDefinitionParameter' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIROperationDefinition/FHIROperationDefinitionParameter.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIROperationDefinition\\FHIROperationDefinitionBinding' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIROperationDefinition/FHIROperationDefinitionBinding.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIROperationParameterUse' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIROperationParameterUse.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIROperationKind' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIROperationKind.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRMedicationAdministration' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRMedicationAdministration.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRMedicationAdministration\\FHIRMedicationAdministrationDosage' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRMedicationAdministration/FHIRMedicationAdministrationDosage.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRElement\\FHIRMedicationAdministrationStatus' => 'App/HL7/FHIR/DSTU2/FHIRElement/FHIRMedicationAdministrationStatus.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRDomainResource\\FHIRRiskAssessment' => 'App/HL7/FHIR/DSTU2/FHIRDomainResource/FHIRRiskAssessment.php',
  'App\\HL7\\FHIR\\DSTU2\\FHIRResource\\FHIRRiskAssessment\\FHIRRiskAssessmentPrediction' => 'App/HL7/FHIR/DSTU2/FHIRResource/FHIRRiskAssessment/FHIRRiskAssessmentPrediction.php',
);

    /** @var bool */
    private static $_registered = false;

    /**
     * @return bool
     * @throws \Exception
     */
    public static function register()
    {
        if (self::$_registered) {
            return self::$_registered;
        }
        return self::$_registered = spl_autoload_register(array(__CLASS__, 'loadClass'), true);
    }

    /**
     * @return bool
     */
    public static function unregister()
    {
        if (self::$_registered) {
            if (spl_autoload_unregister(array(__CLASS__, 'loadClass'))) {
                self::$_registered = false;
                return true;
            }
        }
        return false;
    }

    /**
     * Please see associated documentation for more information on what this method looks for.
     *
     * @param string $class
     * @return bool|null
     */
    public static function loadClass($class)
    {
        if (isset(self::$_classMap[$class]))
            return (bool)require sprintf('%s/%s', self::ROOT_DIR, self::$_classMap[$class]);
        return null;
    }
}